### ISSUE TITLE
Improvemnt | move PROFILE_CONFIG to configmap

### ISSUE THREAD

**Issue by ErezWeiss** [Twingate-Labs/tg-group-profile-manager-helm#3]
Hi!
I'm tired of editing the PROFILE_CONFIG from the K8S secret...
I prefer to do it in git with gitops!
Now it's either using a secret or configmap...
I want the option to take the keys from a secret and the PROFILE_CONFIG from a configmap.

thanks!

**Comment by emrul** [comment]
Thanks @ErezWeiss - we will review and see what can be done.

**Comment by ErezWeiss** [comment]
an offer:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tg-group-profile-manager.fullname" . }}
  labels:
    {{- include "tg-group-profile-manager.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tg-group-profile-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tg-group-profile-manager.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PROFILE_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: profile-config.json
          {{- if not .Values.externalSecretName }}
            - name: TG_ACCOUNT
              value: {{ .Values.variables.twingateAccount }}
            - name: TG_API_KEY
              value: {{ .Values.variables.twingateApiKey }}
            - name: SLACK_SIGNING_SECRET
              value: {{ .Values.variables.slackSigningSecret }}
            - name: SLACK_BOT_TOKEN
              value: {{ .Values.variables.slackBotToken }}
            - name: DEPLOY_ENV
              value: {{ .Values.variables.deployEnv }}
          {{- if .Values.externalSecretName }}
          envFrom:
            - secretRef:
                name: {{ .Values.externalSecretName }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```
